# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian10"
  # config.vm.synced_folder "/Users/stefanpapp/workspace", "/workspace"
  # config.vm.hostname = "confluent1" 
  config.vm.provider "parallels" do |prl|
     prl.memory = "1024"
     prl.name = "confluent"
     prl.update_guest_tools = true
  end
  
  config.vm.provision "shell", inline: <<-SHELL
     export ZSH_CUSTOM:=~/.oh-my-zsh/custom
     apt-get update 

     apt install -y git git-extras fd-find thefuck tig hub wget zplug zsh

     git clone https://github.com/StefanPapp/devops_zshconf ~/devops_zshconf 
     sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

     ln -s ~/devops_zshconf/.zshrc ~/.zshrc

     git clone --depth=1 https://github.com/amix/vimrc.git ~/.vim_runtime
     sh ~/.vim_runtime/install_awesome_vimrc.sh

     git clone https://github.com/zsh-users/zsh-completions ${ZSH_CUSTOM:=~/.oh-my-zsh/custom}/plugins/zsh-completions

     git clone https://github.com/zdharma/fast-syntax-highlighting.git \
  ~ZSH_CUSTOM/plugins/fast-syntax-highlighting

     git clone git://github.com/scmbreeze/scm_breeze.git ~/.scm_breeze
     ~/.scm_breeze/install.sh

     git clone https://github.com/romkatv/powerlevel10k.git $ZSH_CUSTOM/themes/powerlevel10k
   SHELL
end
